version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - docception-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile
      - run: MIX_ENV=test mix compile
      - save_cache:
          key: docception-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
  test:
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - docception-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix test
      - run: ./test.sh
  credo:
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - docception-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix credo --strict
  dialyzer:
    docker:
      - image: circleci/elixir:1.8
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - docception-{{ checksum "mix.lock" }}
            - v1-plt-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix dialyzer --halt-exit-status
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build

workflows:
  version: 2
  verify:
    jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build
      - dialyzer:
          requires:
            - build
